apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "ddns-do.fullname" . }}
  labels:
{{ include "ddns-do.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ddns-do
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: DDNS_DO_TTL
                  value: "300"
                - name: DDNS_DO_DOMAIN
                  value: {{ .Values.domain | quote }}
                - name: DDNS_DO_RECORD
                  value: {{ .Values.record | quote }}
                - name: DIGITALOCEAN_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "ddns-do.fullname" . }}
                      key: access_key
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          restartPolicy: OnFailure
